### PR TITLE
Login

### PR DESCRIPTION
**Pull request by Gaajia**
-login created. 
- basic layout. 
- modal format. 
- doesn't show the background as useEffect handles such as not allowing to scroll when open. when closed the site operates normally. lastly it resets the modal. after closing. 
- added to layout page the useState. to render when open or closed. 

29/10
authService file works with the backend JWT creates a session using localStorage.
registered user appears in the backend using the specific endpoint from the backend. 

image

image

PLEASE ITZI ACCEPT THIS

### CODE REVIEW

**Comment by heyitzi** [comment]
Looks nice! 
What does clicking on sign up to newsletter do? We don't have anything for that in our backend.

**Comment by Gaajia** [comment]
i thought it just looked cool hahaha. i'll take it out. and phone number.

**Comment by heyitzi** [comment]
Can you check the database schema for the fields to be the same? 
We need username as well.

**Comment by heyitzi** [comment]
P.S. The address is optional, and I wouldn't ask for that in the sign up page

**Review by heyitzi — APPROVED** [review]
I'm glad it works!
Whenever you have a moment, please change the style as it's different to the rest of the design. 
Even if we don't have a sign in/up page, you can use the figma file as a reference to style the form and buttons.

**Pull request merged**
